---
- name: Setting up LAMP Website
  hosts: db
  become: yes
  vars:
    ansible_hostname: 0.0.0.0
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Update package repositories for CentOs Linux
      yum:
        name: '*'
        state: latest
      when: "ansible_os_family == 'RedHat' or ansible_os_family == 'CentOs'"

    - name: Determine package name for MariaDB on RedHat/CentOs
      set_fact:
        mariadb_package_name: "{{ 'mariadb-server' if ansible_distribution == 'RedHat' else 'mysql-server' }}"
      when: "ansible_os_family == 'RedHat' or ansible_os_family == 'CentOs'"
 
    - name: Install required packages for CentOs Linux
      yum:
        name:
          - httpd
          - mariadb-server
          - php
          - php-mysql
        state: present
      when: "ansible_os_family == 'RedHat' or ansible_os_family == 'CentOs'"

    - name: Ensure firewalld is installed and enabled (for CentOs Linux)
      package:
        name: firewalld
        state: present
      when: "ansible_os_family == 'RedHat' or ansible_os_family == 'CentOs'"

    - name: Start and enable firewalld (for CentOs Linux)
      service:
        name: firewalld
        enabled: yes
        state: started
      when: "ansible_os_family == 'RedHat' or ansible_os_family == 'CentOs'"

    - name: Allow HTTP traffic in firewalld (for CentOs Linux)
      firewalld:
        service: http
        permanent: yes
        state: enabled
      when: "ansible_os_family == 'RedHat' or ansible_os_family == 'CentOs'"

    - name: Copy mime.types file (for CentOs Linux)
      copy:
        src: /etc/mime.types
        dest: /etc/httpd/conf/mime.types
        remote_src: yes
      when: "ansible_os_family == 'RedHat' or ansible_os_family == 'CentOs'"

    - name: Start and enable Apache for CentOs Linux
      service:
        name: httpd
        enabled: yes
        state: started
      when: "ansible_os_family == 'RedHat' or ansible_os_family == 'CentOs'"
 
    - name: Start and enable MariaDB for CentOs Linux
      service:
        name: mariadb
        enabled: yes
        state: started
      when: "ansible_os_family == 'RedHat' or ansible_os_family == 'CentOs'"

    - name: Download PHP page
      get_url:
        url: "https://www.freecodecamp.org/news/the-best-php-examples/"
        dest: /var/www/html
        mode: 0755
