---
- name: Security patches
  hosts: db
  become: yes

  tasks:
    - name: Update package cache and upgrade security packages on CentOs Linux
      when: "'RedHat' in ansible_facts.os_family"
      yum:
        name: '*'
        state: latest
        security: yes
        update_cache: yes

